### ISSUE TITLE
Buffer not killed after patch executed

### ISSUE THREAD

**Issue by qingshuizheng** [twlz0ne/psearch.el#1]
Hi @twlz0ne ,

After patching a func, the file buffer does not quit. Not sure if it is by design, or we need some cleaning after the patch? 

Here's a test patching `org-insert-structure-template`, to add one "\n" in between org src block header/footer.

Test runs under `Emacs -Q`:

Patch code:
```elisp
(require 'org)
(psearch-patch org-insert-structure-template
     (psearch-replace '`(format "#+%s_%s%s\n" . ,rest)
                      '`(format (if region? "#+%s_%s%s\n" "#+%s_%s%s\n\n") . ,rest)))

```

Buffer list BEFORE patch:

```
  * *scratch*               345 Lisp Interaction 
 %* *Messages*               82 Messages         
```

Buffer-list AFTER patch, and "org.el" is there:

```
  * *scratch*               345 Lisp Interaction 
 %* *Messages*               82 Messages         
    org.el               844087 ELisp/l          /Applications/Emacs.app/Contents/Resources/lisp/org/org.el
```

**Comment by twlz0ne** [comment]
This is indeed a problem.

But before solve it, we need to consider two questions:

1. Files that are already opened before patch should not be closed.
2. If you patch multiple functions from the same file, repeatedly opening & closing file the file will introduce additional overhead.

My suggestion is: keep those opened files but don't let them show up in the buffer list.

```elisp
(defun psearch-patch--xref-function-def (xref-args)
  (let (old-buffer)
    (pcase-let* ((`(,fun ,file ,type) xref-args)
                 (`(,buf . ,pos)
                  (cl-letf* ((orig-ffnosel (symbol-function #'find-file-noselect))
                             ((symbol-function #'find-file-noselect)
                              (lambda (&rest args)
                                (setq old-buffer (get-file-buffer (car args)))
                                (apply orig-ffnosel args))))
                    (find-function-search-for-symbol fun type file))))
      (with-current-buffer buf
        (goto-char pos)
        (let ((bounds (bounds-of-thing-at-point 'sexp)))
          (prog1 (read (buffer-substring-no-properties (car bounds) (cdr bounds)))
            ;; Hide file from buffer list if the file was opened by psearch-patch.
            (unless (or old-buffer (string-prefix-p " " (buffer-name)))
              (rename-buffer (concat " " (buffer-name))))))))))
```

**Comment by qingshuizheng** [comment]
> we need to consider two questions

You're right, make sense.


> but don't let them show up in the buffer list.

The fix works perfect, I'll take that.

Thanks for the suggestion.

**Comment by twlz0ne** [comment]
> The fix works perfect, I'll take that.

Unfortunately I found it it not works perfect.

Reproduce:

1. Open file `org.el.lgz` by execute `M-: (psearch-patch--find-function 'org-insert-structure-template)`.
2. Visit `org.el.gz` manually (`M-x describe-function ...`).
3.  Switch to last buffer.
4. Press `C-x b` to switch buffer.
5. You will not see the buffer `org.el.gz` in completion list.

**Comment by qingshuizheng** [comment]
> 5\. You will not see the buffer `org.el.gz` in completion list.


Can confirm. 

Before any improvement is available, I'm okay with that. 😃 
At least it won't pop up any unwanted buffers.

Thanks for the update.
